log_dir: "Models/A2L_M30_gn"
save_freq: 20
device: "cuda"
epochs: 200
batch_size: 64
pretrained_model: ""
load_only_params: false
fp16_run: true

# train_data: "Data/train_emo_list_0.txt"
# val_data: "Data/val_emo_list_0.txt"
train_data: "Data/train_emo_list_M30.txt"
val_data: "Data/val_emo_list_M30.txt"

F0_path: "Utils/JDC/bst.t7"
ASR_config: "Utils/ASR/config.yml"
ASR_path: "Utils/ASR/epoch_00100.pth"

preprocess_params:
  sr: 24000
  spect_params:
    n_fft: 2048
    win_length: 1200
    hop_length: 800

model_params:
  dim_in: 64
  style_dim: 64
  latent_dim: 16
  num_domains: 8
  max_conv_dim: 512
  n_repeat: 4
  w_hpf: 0
  F0_channel: 256

loss_params:
  g_loss:
    lambda_sty: 1.
    lambda_cyc: 5.
    lambda_ds: 1.
    lambda_norm: 1.
    lambda_asr: 10.
    lambda_f0: 5.
    lambda_f0_sty: 0.1
    lambda_adv: 2.
    lambda_adv_cls: 0.5
    norm_bias: 0.5
  d_loss:
    lambda_reg: 1.
    lambda_adv_cls: 0.1
    lambda_con_reg: 10.
  
  adv_cls_epoch: 5
  con_reg_epoch: 3

optimizer_params:
  lr: 0.0002
  T_0: 200
  T_mult: 1
#   epochs: 200
#   pct_start: 0.3
#   div_factor: 20
#   final_div_factor: 1
  #steps_per_epoch: 1000 # len(train_dataloader)
